### ISSUE TITLE
Врачи(дурка)

### ISSUE THREAD

**Issue by vaseQ-NotAllow** [speedy-hackathon/first-app#16]
Добавить врачей и больницу. Когда врач встречает заражённого он забирает его в дурку и запирает там, пока он не вылечится или не умрёт(если нет задания про смерть и выздоровления, то добавить их)
*У врачей не сто процентный шанс обнаружить инфекцию, например чем меньше человек заражён тем меньше шанс того, что его посадят.

**Comment by Aminopyridin** [comment]
Врачи у нас есть в задачах. Но они пока лечат по пути. А вот больниц нету. 
Опиши отдельно задачу про больницы.
