### ISSUE TITLE
Бред(хватит этих идей)

### ISSUE THREAD

**Issue by vaseQ-NotAllow** [speedy-hackathon/first-app#18]
Добавить безумных фанатиков, которые верят, что ковид распространяется из-за 5g вышек, эти фанатики будут ходить по городу и учинять беспорядки, на первых порах хватит того, что они имеют шанс убить любого человека, которого встретят.

**Comment by Aminopyridin** [comment]
Ой, у нас итак скоро будет много типов человечков. Давай не будем усложнять)
