### ISSUE TITLE
Лекарство есть, но это не точно(8 команда)

### ISSUE THREAD

**Issue by vaseQ-NotAllow** [speedy-hackathon/first-app#29]
Добавить прогресс создания вакцины. Существуют научные лаборатории, которые пассивно дают прогресс лекарства.
*Иногда появляется возможность кликнуть на лабу и получить буст к исследованиям

**Comment by Aminopyridin** [comment]
Непонятно, как работает вакцина

**Comment by vaseQ-NotAllow** [comment]
Если процесс создания вакцины дойдёт до конца все излечатся и победа в игре

**Comment by Aminopyridin** [comment]
Ну, блин, это тоже из другой игры) совсем-то уж плагиатить не надо

**Comment by vaseQ-NotAllow** [comment]
Никакого плагиата) Только с текущей ситуации в мире))
