### ISSUE TITLE
Чхал я на вас(8 команда)

### ISSUE THREAD

**Issue by vaseQ-NotAllow** [speedy-hackathon/first-app#34]
Добавить возможность чихать. Когда человек чихнул после него на 7 тиков остаётся облако, если  он был заражён, то люди, которые пройдут через облако могу заразиться. Люди в масках не чихают.

**Comment by Aminopyridin** [comment]
Так люди итак заражаются, если пройдут недалеко от больного персонажа

**Comment by Aminopyridin** [comment]
Облако — прикольно, но нужно ему какую-то механику прикольную придумать

**Comment by vaseQ-NotAllow** [comment]
Облоко - это человек, который живёт три тика) И движется с неизменным направлением))))
