### ISSUE TITLE
Задача 21. Идем за покупочками

### ISSUE THREAD

**Issue by GangBoss** [speedy-hackathon/first-app#36]
Зависит от задач: -

Описание задачи 
Человечки, которые гуляют, Бродят бездумно. Им явно нужна цель. Сделай магазины в которые человечки смогут ходить.
Нужно сделать так, чтобы человечки, выходящие на прогулку уходили в магазин и на каждый тик перемещались в его сторону, а потом шлялись внутри магазина
Они могут ходить по кругу или в случайную точку магазина — решай сам, как именно.. 
Стоимость задачи
5 балла

**Comment by Aminopyridin** [comment]
И зачем ты почти полностью скопировал текст имеющейся задачи?

**Comment by GangBoss** [comment]
Цель задачи: добавить новый объект в который будут уходить люди (магазин, который отличается от обычных домов)
Поскольку после задачи 3 новые социальные контакты в домах не появляются магазин может стать новым рассадником заразы

Пересечения с задачей 2 в текстовом описании были добавлены для сохранения стилистики прошлых задач (так сказать Бац бац и в продакшен)

**Comment by GangBoss** [comment]
Только сейчас получили "16 Магазины", до этого не знал что существует такая задача, упс
