### ISSUE TITLE
Превентивные меры(8 команда)

### ISSUE THREAD

**Issue by vaseQ-NotAllow** [speedy-hackathon/first-app#39]
Помнить варик третий? Там был очень хороший метод борьбы с чумой.
Давайте добавим и его в наше приложение.
Добавить панель инструментов, в которой можно выбирать тип клика: сжигать, отправлять домой, станить, заражать.
Но звучит как-то слишком сложно.

**Comment by Aminopyridin** [comment]
Не, ну сейчас у нас симулятор мента. А ты хочешь симулятор бога)
