### ISSUE TITLE
Я знаю пароль(8 команда)

### ISSUE THREAD

**Issue by vaseQ-NotAllow** [speedy-hackathon/first-app#43]
Помните в третьй задаче мы запретили людям ходить по чужим домам?
Но некоторых людей это запрет не остановил, ведь у них есть ключи от некоторых домов.
Такие люди могут заходить в некоторые дома и заражать тамошних жильцов.

**Comment by Aminopyridin** [comment]
Слишком сложно для отслеживания и для настройки будет. Каждый человечек кроме родного дома должен еще и какими-то доступными ему домами обладать...
