### ISSUE TITLE
Команда 3, баг в формулировке задачи 14

### ISSUE THREAD

**Issue by Pasha0666** [speedy-hackathon/first-app#51]
В задаче 10 нет вероятности вылечиться, а в 14 она появляется не откуда)

**Comment by hariton27sy** [comment]
Это не баг это фича

**Comment by Aminopyridin** [comment]
Вероятность вылечиться появляется в 6 задаче и для реализации врачей (10) не обязательно, чтобы она была реализована сама по себе. 
На сервере сейчас должны выздоравливать человечки через 35 ходов
