### ISSUE TITLE
Предложение для задачи

### ISSUE THREAD

**Issue by vaseQ-NotAllow** [speedy-hackathon/first-app#9]
Добавить возможность создание кастомных карт. Напрямую в браузере и(или) выгрузку из какого-нибудь локального файла.

**Comment by vaseQ-NotAllow** [comment]
Добавить заражённых людей, если заражённый встречается с простым чуваком, он становится заражённым с некоторым шансом.

**Comment by vaseQ-NotAllow** [comment]
Добавить аксессуары для людей, по типу масок и всего прочего, которые уменьшают шанс заразиться.

**Comment by Aminopyridin** [comment]
Ну, и как я три задачи смогу оценивать? Давай по отдельности. 
Вторая задача у нас уже есть, а первую и третью норм идеи, но нужно расписать подробнее.
